---
- name: Deploy Nginx with Prometheus Exporter
  hosts: localhost
  connection: local
  tasks:
    - name: Create Nginx ConfigMap for metrics
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: nginx-conf
            namespace: web
          data:
            default.conf: |
              server {
                  listen 80;
                  location / { root /usr/share/nginx/html; index index.html; }
                  location /nginx_status { 
                      stub_status on; 
                      access_log off; 
                      allow 127.0.0.1; 
                      deny all; 
                  }
              }

    - name: Deploy Nginx and Exporter Pod (Sidecar)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-web
            namespace: web
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx-web
            template:
              metadata:
                labels:
                  app: nginx-web
              spec:
                containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                  - containerPort: 80
                  volumeMounts:
                  - name: conf
                    mountPath: /etc/nginx/conf.d
                - name: exporter
                  image: nginx/nginx-prometheus-exporter:latest
                  args: ["-nginx.scrape-uri=http://127.0.0.1:80/nginx_status"]
                  ports:
                  - containerPort: 9113
                volumes:
                - name: conf
                  configMap:
                    name: nginx-conf

    - name: Create Unified Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: web
          spec:
            selector:
              app: nginx-web
            ports:
            - name: http
              port: 80
            - name: metrics
              port: 9113

    - name: Create Ingress (Fixing path conflicts)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: nginx-ingress
            namespace: web
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            ingressClassName: nginx
            rules:
            - http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: nginx-service
                      port:
                        number: 80
