---
- import_playbook: playbooks/01-k8s-cluster.yml
- import_playbook: playbooks/02-namespaces.yml
- import_playbook: playbooks/03-monitoring.yml
- import_playbook: playbooks/04-nginx.yml
- import_playbook: playbooks/05-etcd.yml
- import_playbook: playbooks/nginx-english-dashboard.yml
