all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    project_dir: "{{ playbook_dir }}/.."
    k8s_dir: "{{ project_dir }}/k8s"
    kubeconfig: /etc/kubernetes/admin.conf
    pod_cidr: "10.244.0.0/16"
    k8s_version: "1.30"
